---
title: "Data Pre-Processing_Final"
output: html_document
---

```{r}
library(readxl)
ADS_Project_11_29_2021_v8 <- read_excel("ADS_Project - 11.29.2021.v8.xlsx") %>%
  mutate(Date = ymd(Date))
```


```{r}
Master.v8 <- ADS_Project_11_29_2021_v8 %>%
select(-c(`Last Calculated EOD metrics (time, in seconds)`, `Block Count`, `Block Size (mean, in bytes)`, `Block Weight, (mean`, `Capitalization of current supply, MVRV`, `Capitalization of free float, MVRV`, `Difficulty, Last Block`, `Difficulty, Mean Block`, `Mean Transaction Fee per Byte of all blocks, native units`, `Mean Transaction Fee per Byte, native units`, `Median Transaction Fee, native units`, `Median Fee per Transacation, USD`, `Addresses balance greater than 0.001 native units`, `Addresses balance greater than 0.01 native units`, `Addresses balance greater than 0.1 native units`,`Addresses balance greater than 100 native units`, `Addresses balance greater than 100K native units`, `Addresses balance greater than 10 native units`, `Addresses balance greater than 10K native units`, `Addresses balance greater than 1 native units`, `Addresses balance greater than 1K native units`, `Addresses balance greater than 1M native units`, `Addresses balance greater than 1in100K`, `Addresses balance greater than 1in100M`, `Addresses balance greater than 1in10B`, `Addresses balance greater than 1in10K`, `Addresses balance greater than 1in10K`, `Addresses balance greater than 1in10M`, `Addresses balance greater than 1in1B`, `Addresses balance greater than 1in1K`, `Addressesbalance greater than 1in1M`, `Total Fees, native units`, `Flow to exchanges, native units`, `Flow out exchanges, native units`, `Gas Limit Block`, `Gas Limit, transaction`, `Gas Used, transaction`, `Hash Rate Mean, 30d`, `Issuance, native units`, `Issuance, percent annualized`, `Issuance,  percent daily`, `Issuance Total, native units`,`NVT, adjusted, 90d MA`, `NVT, adjusted, free float,  90d MA`, `ROI, 1y (%)`, `Revenue, per hash unit (Native Currency)`, `Revenue Daily, per hash unit/second (Native Currency)`, `Miner Rev (Native Currency)`, `Supply, 10y Active`, `Supply, 5yr Active`, `Supply, 4yr Active`, `Supply, 3yr Active`, `Supply, 1yr Active Trailing (%)`, `Supply, in addresses (<0.001, native currency)`, `Supply, in addresses (<0.01M, native currency)`, `Supply, in addresses (<0.1, native currency)`, `Supply, in addresses (<1, native currency)`, `Supply, in addresses (<10, native currency)`, `Supply, in addresses (<100, native currency)`, `Supply, in addresses (<100K, native currency)`, `Supply, in addresses (<10K, native currency)`, `Supply, in addresses (<1K, native currency)`, `Supply, in addresses (<1M, native currency)`, `Supply, Miner address with 1 mining entity (native currency)`, `Supply, All Miners (native currency)`, `Transactions, adjusted transfer value (native currency)`, `Transactions, mean transfer value (native currency)`, `Transactions, median transfer value (native currency)`, `Transactions, mean transfer value ($)`, `Transactions, median transfer value (native currency)`, `Velocity, 1yr current supply`, `Volatility, 180d daily returns`, `Volatility, 30d daily returns`, `Price, BTC`, `Transactions, median transfer value ($)`, `Price, ($)`))
```


<br> Data Exploration & Initial Visualizations

```{r}
p1 <- ggplot(Master.v8,
       aes(x = `Block, weight, total`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Block Weight"))

p2 <- ggplot(Master.v8,
       aes(x = `Mean Fee per Transaction, USD`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Mean Transaction Fee"))

p3 <- ggplot(Master.v8,
       aes(x = `Total Fees, USD`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Total Fees"))

p4 <- ggplot(Master.v8,
       aes(x = `Gas Limit Block, mean`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Mean Gas Limit Block"))

p5 <- ggplot(Master.v8,
       aes(x = `Gas limit Mean, transaction`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Transaction Gas Limit Mean"))

p6 <- ggplot(Master.v8,
       aes(x = `Mean Gas Used, transaction`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~.*1000, name = "Mean Gas Used"))

p7 <- ggplot(Master.v8,
       aes(x = `Hash Rate, mean`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Hashate Rate"))

p8 <- ggplot(Master.v8,
       aes(x = `Issuance, in USD`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Issuance (USD)"))

p9 <- ggplot(Master.v8,
       aes(x = `Issuance Total, in USD`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Total Issuance"))

p10 <- ggplot(Master.v8,
       aes(x = `NVT, adjusted`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "NVT Adjusted"))

p11 <- ggplot(Master.v8,
       aes(x = `NVT, adjusted, free float`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "NVT Free Float Adjusted"))

p12 <- ggplot(Master.v8,
       aes(x = `ROI, 30D (%)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "30D ROI"))

p13 <- ggplot(Master.v8,
       aes(x = `Miner Rev, Total ($)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Miner Revenue"))

p14 <- ggplot(Master.v8,
       aes(x = `Revenue Daily, per hash unit/second (USD)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Hashate Rate"))

p15 <- ggplot(Master.v8,
       aes(x = `Revenue, per hash unit ($)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Hashate Rate"))

p16 <- ggplot(Master.v8,
       aes(x = `Supply Equality Ratio`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Hashate Rate"))

p17 <- ggplot(Master.v8,
       aes(x = `Supply, 180D Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 180D Active"))

p18 <- ggplot(Master.v8,
       aes(x = `Supply, 1D Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 1D Active"))

p19 <- ggplot(Master.v8,
       aes(x = `Supply, 1yr Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 1yr Active"))

p20 <- ggplot(Master.v8,
       aes(x = `Supply, 2y Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 2yr Active"))

p21 <- ggplot(Master.v8,
       aes(x = `Supply, 30D Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 30D Active"))

p22 <- ggplot(Master.v8,
       aes(x = `Supply, 7D Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 7D Active"))

p23 <- ggplot(Master.v8,
       aes(x = `Supply, 90D Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 90D Active"))

p24 <- ggplot(Master.v8,
       aes(x = `Supply, Total Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, Total Active"))

p25 <- ggplot(Master.v8,
       aes(x = `Supply, 1yr Active`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 1yr Active"))

p26 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in100K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in100K"))

p27 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in100M)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in100M)"))

p28 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in10B)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in10B)"))

p29 <-ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in10K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in10K)"))

p30 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in10M)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in10M)"))

p31 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in1B)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in1B)"))

p32 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in1K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in1K)"))

p33 <- ggplot(Master.v8,
       aes(x = `Supply, address balance (<1in1M)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, address balance (<1in1M)"))

p34 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$1)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$1)"))

p35 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$10)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$10)"))

p36 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$100)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$100)"))

p37 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$100K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$100K)"))

p38 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$10K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$10K)"))

p39 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$10M)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$10M)"))

p40 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$1K)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$1K)"))

p41 <- ggplot(Master.v8,
       aes(x = `Supply, in addresses (<$1M)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, in addresses (<$1M)"))

p42 <- ggplot(Master.v8,
       aes(x = `Supply, held by top 100 addresses`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, held by top 100 addresses"))

p43 <- ggplot(Master.v8,
       aes(x = `Supply, held by top 10% addresses`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, held by top 10% addresses"))

p44 <- ggplot(Master.v8,
       aes(x = `Supply, held by top 1% addresses`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, held by top 1% addresses"))

p45 <- ggplot(Master.v8,
       aes(x = `Supply, current`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Current Supply"))

p46 <- ggplot(Master.v8,
       aes(x = `Supply, 10yr expected supply`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, 10yr expected supply"))

p47 <- ggplot(Master.v8,
       aes(x = `Supply, free float`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, free float"))

p48 <- ggplot(Master.v8,
       aes(x = `Supply, All Miners ($)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, All Miners"))

p49 <- ggplot(Master.v8,
       aes(x = `Supply, Miner address with 1 mining entity ($)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Supply, Miner address with 1 mining entity ($)"))

p50 <- ggplot(Master.v8,
       aes(x = `Transactions, count`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Transactions, count"))

p51 <- ggplot(Master.v8,
       aes(x = `Transactions, count (per second)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Transactions, count (per second)"))

p52 <- ggplot(Master.v8,
       aes(x = `Transactions, transfer count`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Transactions, transfer count"))

p53 <- ggplot(Master.v8,
       aes(x = `Transactions, adjusted transfer value ($)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Transactions, adjusted transfer value ($)"))

p54 <- ggplot(Master.v8,
       aes(x = `Coin_Days_Destroyed`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Coin Days Destroyed"))

p55 <- ggplot(Master.v8,
       aes(x = `Balance_Exchanges_(%)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Balance on Exchanges (%)"))

p56 <- ggplot(Master.v8,
       aes(x = `Total_Exchange_Inflow_Volume`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Exchange Inflow Volume"))

p57 <- ggplot(Master.v8,
       aes(x = `SOPR`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "SOPR"))

p58 <- ggplot(Master.v8,
       aes(x = `Adjusted_Dormancy_Flow`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Adjusted Dormancy Flow"))

p59 <- ggplot(Master.v8,
       aes(x = `Coin_Years_Destroyed`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Coin_Years_Destroyed"))

p60 <- ggplot(Master.v8,
       aes(x = `NUPL`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "NUPL"))

p61 <- ggplot(Master.v8,
       aes(x = `rHODL`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "rHODL"))

p62 <- ggplot(Master.v8,
       aes(x = `CPI`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "CPI"))

p63 <- ggplot(Master.v8,
       aes(x = `CPI_(%)`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "CPI(%)"))


p64 <- ggplot(Master.v8,
       aes(x = `BTC(%)`,
           y = `Price`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "BTC (%)"))

p65 <- ggplot(Master.v8,
       aes(x = `NDQ(%)`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Nasdaq (%)"))

p66 <- ggplot(Master.v8,
       aes(x = `Gold(%)`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Gold (%)"))

p67 <- ggplot(Master.v8,
       aes(x = `BTC_Searches`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "BTC Searches"))

p68 <- ggplot(Master.v8,
       aes(x = `BTCS(%)`,
           y = `BTC(%)`)) + 
         geom_point() + 
         geom_smooth(method = lm, se = FALSE) +
   scale_y_continuous("Price", sec.axis = sec_axis(~., name = "Bitcoin Searches (%)"))



p1 + p2 + p3 + p4 + p5

p6 + p7 + p8 + p9 + p10

p11 + p12 + p13 + p14 + p15

p16 + p17 + p18 + p19 + p20

p21 + p22 + p23 + p24 + p25

p26 + p27 + p28 + p29 + p30

p31 + p32 + p33 + p34 + p35

p36 + p37 + p38 + p39 + p40

p41 + p42 + p43 + p44 + p45

p46 + p47 + p48 + p49 + p50

p51 + p52 + p53 + p54 + p55

p56 + p57 + p58 + p59 + p60

p61 + p62 + p63 + p64 + p65

p66 + p67 + p68



```

<br> Additional Cleaning

Based on the graphs above, we can identify variables that are strongly correlated and some that have almost no correlation at all. 

```{r}
Master.v9 <- Master.v8 %>% select(-c(`Gas limit Mean, transaction`, `Hash Rate, mean`, `Issuance, in USD`, `Issuance Total, in USD`, `ROI, 30D (%)`, `Revenue Daily, per hash unit/second (USD)`, `Revenue, per hash unit ($)`, `Supply Equality Ratio`, `Supply, 180D Active`, `Supply, 1yr Active`, `Supply, 2y Active`, `Supply, 1yr Active`, `Supply, Miner address with 1 mining entity ($)`, `Transactions, count`,`Transactions, count (per second)`, `Transactions, adjusted transfer value ($)`, `Coin_Days_Destroyed`, `Balance_Exchanges_(%)`, `Total_Exchange_Inflow_Volume`, `Supply, 30D Active`, `Supply, 7D Active`, `Supply, 90D Active`, `Supply, address balance (<1in10K)`, `Supply, address balance (<1in10M)`, `Supply, address balance (<1in10B)`, `Supply, address balance (<1in10K)`, `Supply, address balance (<1in1B)`, `Supply, address balance (<1in1K)`, `Supply, address balance (<1in1M)`, `Supply, in addresses (<$1)`, `Supply, in addresses (<$10)`, `Supply, in addresses (<$100)`, `Supply, in addresses (<$100K)`, `Supply, in addresses (<$10K)`, `Supply, in addresses (<$10M)`, `Supply, in addresses (<$1K)`, `Supply, held by top 1% addresses`, `Supply, 10yr expected supply`, `Supply, free float`, `Supply, All Miners ($)`, `Supply, Miner address with 1 mining entity ($)`, `Transactions, count`, `Transactions, adjusted transfer value ($)`, `Coin_Days_Destroyed`, `CPI_(%)`))
```

